version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.10

jobs:
  build-and-deploy:
    executor: python-executor
    steps:
      - checkout

      # Deploy to a new directory with the current date
      - run:
          name: Deploy application
          command: |
            DEPLOY_DIR="DEPLOY_$(date +'%Y%m%d')"
            mkdir "$DEPLOY_DIR"
            cp -r . "$DEPLOY_DIR"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
